### PR TITLE
Update doc scripts

### PR DESCRIPTION
**Pull request by ashtum**

### CODE REVIEW

**Comment by vinniefalco** [comment]
Well if this works, then I like it.

**Comment by vinniefalco** [comment]
build_antora.sh still doesn't work for me:

```
$ ./build_antora.sh
No playbook supplied, using default playbook
Building documentation with Antora...
Installing npm dependencies...

added 3 packages, removed 1 package, changed 23 packages, and audited 283 packages in 3s

41 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (9 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
Building docs in custom dir...
{"level":"fatal","time":1712587245336,"name":"antora","hint":"Add the --stacktrace option to see the cause of the error.","msg":"(@antora/collector-extension): Command failed: C:\\Windows\\system32\\cmd.exe /d /s /c \"\"C:\\Program Files\\nodejs\\node.exe\" doc/generate-files.mjs\" in C:\\Users\\Vinnie\\src\\boost\\libs\\buffers (branch: develop <worktree> | start path: doc)\nINFO: Could not find files for the given pattern(s).\r\nINFO: Could not find files for the given pattern(s).\r\nINFO: Could not find files for the given pattern(s).\r\nnode:internal/errors:490\r\n    ErrorCaptureStackTrace(err);\r\n    ^\r\n\r\nTypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received undefined\r\n    at new NodeError (node:internal/errors:399:5)\r\n    at validateString (node:internal/validators:163:11)\r\n    at Object.basename (node:path:752:5)\r\n    at file:///C:/Users/Vinnie/src/boost/libs/buffers/doc/generate-files.mjs:103:30\r\n    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {\r\n  code: 'ERR_INVALID_ARG_TYPE'\r\n}\r\n\r\nNode.js v18.15.0\r\n"}
Done
```

**Comment by ashtum** [comment]
Could you please test the following in CMD (doesn't work in PowerShell):
```BAT
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
set PATH=%PATH%;C:\Program Files\7-Zip\
npx antora --clean --fetch local-playbook.yml
```

**Comment by vinniefalco** [comment]
Yes! That got me to compiling the library using MrDox. But there are compile errors.

**Pull request merged**
